create table "public"."promos" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text,
    "description" text,
    "price" double precision,
    "new_price" double precision
);


alter table "public"."promos" enable row level security;

CREATE UNIQUE INDEX promos_pkey ON public.promos USING btree (id);

alter table "public"."promos" add constraint "promos_pkey" PRIMARY KEY using index "promos_pkey";

grant delete on table "public"."promos" to "anon";

grant insert on table "public"."promos" to "anon";

grant references on table "public"."promos" to "anon";

grant select on table "public"."promos" to "anon";

grant trigger on table "public"."promos" to "anon";

grant truncate on table "public"."promos" to "anon";

grant update on table "public"."promos" to "anon";

grant delete on table "public"."promos" to "authenticated";

grant insert on table "public"."promos" to "authenticated";

grant references on table "public"."promos" to "authenticated";

grant select on table "public"."promos" to "authenticated";

grant trigger on table "public"."promos" to "authenticated";

grant truncate on table "public"."promos" to "authenticated";

grant update on table "public"."promos" to "authenticated";

grant delete on table "public"."promos" to "service_role";

grant insert on table "public"."promos" to "service_role";

grant references on table "public"."promos" to "service_role";

grant select on table "public"."promos" to "service_role";

grant trigger on table "public"."promos" to "service_role";

grant truncate on table "public"."promos" to "service_role";

grant update on table "public"."promos" to "service_role";


